tasks:
  - init: python2 -m pip install -U pip wheel setuptools
  - init: python2 -m pip install -U mercurial<5 hggit
  - init: hg clone https://hg.openjdk.java.net/code-tools/trees ~/trees
  - init: "echo \"[extensions]\"\ntrees = ~/trees/trees.py\nhggit ="
